"""Keep the hash-locked headless requirements an exact export of ``uv.lock``.

``desktop-electron/requirements-headless.txt`` has two consumers:

* the ``electron-migration-tests`` workflow job, which builds a Qt-free
  interpreter with ``uv pip sync --require-hashes`` and drives the Python core
  through the Electron IPC contract, and
* ``packaging/linux/build.py``, which reads its pins to decide the PyInstaller
  ``--copy-metadata`` set.

Nothing compared that file with ``uv.lock``, so it drifted silently: 23 of its
32 pins named a different version than the lock, ``setproctitle`` and
``watchdog`` (both runtime dependencies of this project) were missing entirely,
and ``cloudpickle`` was pinned without being a dependency of anything. The
migration lane therefore exercised a different library set than the gated lane
while both reported success.

The file is generated from the lock rather than resolved from
``requirements-headless.in``, so these tests recompute the lock's runtime
closure for the interpreter both lanes use (CPython 3.12) and require the file to
match it exactly.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path
from typing import Any

from packaging.markers import Marker

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "uv.lock"
REQUIREMENTS = ROOT / "desktop-electron" / "requirements-headless.txt"
FREEZER_INPUTS = (
    ROOT / "packaging" / "linux" / "requirements-build.in",
    ROOT / "packaging" / "macos" / "requirements-build.in",
)
FREEZER_LOCKS = (
    ROOT / "packaging" / "linux" / "requirements-build.txt",
    ROOT / "packaging" / "macos" / "requirements-build.txt",
)
COMPILED_FREEZER_LOCK = ROOT / "packaging" / "linux" / "requirements-build.txt"

# Both the release gate and the Electron CI job run CPython 3.12 on CPython, so the
# expectation must not depend on the interpreter that happens to run pytest. Without
# pinning these, a developer on 3.13 would include the ``standard-*`` backports the
# lock marks as 3.13-only and see a spurious failure.
TARGET_ENVIRONMENT = {
    "python_version": "3.12",
    "python_full_version": "3.12.0",
    "implementation_name": "cpython",
}

_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)", re.MULTILINE)
_HASH = re.compile(r"--hash=(sha256:[0-9a-f]+)")


def _key(name: str) -> str:
    """Normalize a distribution name the way the lock's ``name`` field never varies."""
    return name.lower().replace("_", "-")


def _lock_packages() -> dict[str, dict[str, Any]]:
    return {_key(package["name"]): package for package in tomllib.loads(LOCK.read_text(encoding="utf-8"))["package"]}


def _runtime_closure() -> set[str]:
    """Every registry package reachable from the project's runtime dependencies on 3.12."""
    packages = _lock_packages()
    project_name = _key(tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["name"])
    assert project_name in packages, f"{project_name} is missing from uv.lock"

    seen: set[str] = set()
    pending = [project_name]
    while pending:
        name = pending.pop()
        if name in seen or name not in packages:
            continue
        seen.add(name)
        for edge in packages[name].get("dependencies", []):
            marker = edge.get("marker")
            if marker is not None and not Marker(marker).evaluate(TARGET_ENVIRONMENT):
                continue
            pending.append(_key(edge["name"]))
    return seen - {project_name}


def _pins(path: Path = REQUIREMENTS) -> dict[str, tuple[str, str]]:
    """Map each pinned package to its version and its full requirement block."""
    text = path.read_text(encoding="utf-8")
    matches = list(_PIN.finditer(text))
    pins: dict[str, tuple[str, str]] = {}
    for index, match in enumerate(matches):
        stop = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        name = _key(match.group(1))
        assert name not in pins, f"Duplicate pin in {path.name}: {name}"
        pins[name] = (match.group(2), text[match.end() : stop])
    return pins


def test_headless_requirements_declare_themselves_a_lock_export() -> None:
    header = "\n".join(REQUIREMENTS.read_text(encoding="utf-8").splitlines()[:3])

    assert "autogenerated by uv" in header
    assert "uv export" in header, (
        "requirements-headless.txt must be exported from uv.lock so it cannot drift; "
        "resolving requirements-headless.in pins whatever is newest on PyPI instead"
    )


def test_headless_requirements_pin_exactly_the_locked_runtime_closure() -> None:
    expected = _runtime_closure()
    actual = set(_pins())

    missing = sorted(expected - actual)
    extra = sorted(actual - expected)
    assert not missing and not extra, (
        "requirements-headless.txt no longer matches the runtime closure of uv.lock: "
        f"missing {missing}, unexpected {extra}"
    )


def test_headless_requirements_pin_the_locked_versions() -> None:
    packages = _lock_packages()
    drift = {
        name: (version, packages[name]["version"])
        for name, (version, _block) in _pins().items()
        if name in packages and packages[name]["version"] != version
    }

    assert not drift, f"headless pins disagree with uv.lock (pin, locked): {drift}"


def test_headless_requirements_hash_only_locked_artifacts() -> None:
    packages = _lock_packages()
    for name, (version, block) in _pins().items():
        hashes = set(_HASH.findall(block))
        assert hashes, f"{name}=={version} is pinned without any sha256 artifact hash"

        package = packages[name]
        assert package["version"] == version, f"{name}=={version} is not the version uv.lock pins"
        locked_hashes = {wheel["hash"] for wheel in package.get("wheels", [])}
        if "sdist" in package:
            locked_hashes.add(package["sdist"]["hash"])
        unknown = sorted(hashes - locked_hashes)
        assert not unknown, f"{name}=={version} carries hashes uv.lock does not record: {unknown}"


def test_freezer_inputs_only_restate_locked_versions() -> None:
    """The PyInstaller freezer inputs re-pin a few packages beside the headless include.

    ``packaging/linux/requirements-build.in`` and its macOS sibling start with
    ``-r ../../desktop-electron/requirements-headless.txt`` and then add the freezer
    toolchain. A pin that contradicts the lock (``packaging==26.3`` next to a locked
    ``25.0``) makes ``uv pip compile`` fail with an unsatisfiable requirement set, so
    the pin has to agree with ``uv.lock`` even though the compiled ``.txt`` is the file
    the freezer lanes actually install.
    """
    packages = _lock_packages()
    for path in FREEZER_INPUTS:
        contradictions: list[str] = []
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("-r "):
                continue
            name, separator, version = line.partition("==")
            if not separator or not version:
                contradictions.append(f"{line} (not an exact pin)")
                continue
            locked = packages.get(_key(name))
            if locked is None:
                contradictions.append(f"{name} (absent from uv.lock)")
            elif locked["version"] != version:
                contradictions.append(f"{name}=={version} (uv.lock pins {locked['version']})")

        assert not contradictions, f"{path.relative_to(ROOT)} contradicts uv.lock: {contradictions}"


def test_compiled_freezer_lock_is_a_hash_locked_export() -> None:
    """The compiled Linux lock has to stay a hash-locked ``uv pip compile`` export.

    ``packaging/linux/build.py`` installs this file with ``--require-hashes``, so a pin
    without a hash is an install-time failure, and a hand-edited file loses the ability
    to be regenerated by the command its own header records.
    """
    text = COMPILED_FREEZER_LOCK.read_text(encoding="utf-8")
    header, _, command = "\n".join(text.splitlines()[:2]).partition("\n")
    blocks = _pins(COMPILED_FREEZER_LOCK)

    assert "autogenerated by uv" in header
    assert "uv pip compile --generate-hashes" in command, (
        "the header must record a hash-generating regeneration command"
    )
    assert (
        str(COMPILED_FREEZER_LOCK.relative_to(ROOT)) in command and str(FREEZER_INPUTS[0].relative_to(ROOT)) in command
    ), "the header command must name the freezer input and this output"
    unhashed = sorted(name for name, (_version, block) in blocks.items() if not _HASH.search(block))
    assert not unhashed, f"{COMPILED_FREEZER_LOCK.name} pins without a hash: {unhashed}"


def test_compiled_freezer_lock_agrees_with_the_headless_snapshot() -> None:
    """A stale compiled lock is how the freezer lane silently ran a different closure.

    The committed ``.txt`` pinned 23 versions the headless snapshot did not name
    (``certifi==2026.7.22`` against ``2026.5.20``) and had no pin at all for
    ``setproctitle`` and ``watchdog``, while both the mirrored lane job and the freezer
    lane reported success. Only regenerating the file fixes that, so this test pins the
    agreement instead of trusting the file.
    """
    snapshot = _pins()
    compiled = _pins(COMPILED_FREEZER_LOCK)

    missing = sorted(name for name in snapshot if name not in compiled)
    contradictory = sorted(
        f"{name}=={version} (snapshot pins {snapshot[name][0]})"
        for name, (version, _block) in compiled.items()
        if name in snapshot and snapshot[name][0] != version
    )

    assert not missing, f"{COMPILED_FREEZER_LOCK.name} omits headless pins: {missing}"
    assert not contradictory, (
        f"{COMPILED_FREEZER_LOCK.name} no longer matches requirements-headless.txt: {contradictory}"
    )


def test_macos_freezer_lock_includes_the_linux_lock_and_only_adds_darwin() -> None:
    """macOS reuses the Linux hashes and adds the one Darwin-only freezer dependency."""
    text = (ROOT / "packaging" / "macos" / "requirements-build.txt").read_text(encoding="utf-8")
    included = ROOT / "packaging" / "macos" / ".." / "linux" / "requirements-build.txt"

    assert "-r ../linux/requirements-build.txt" in text
    assert included.resolve().is_file(), "the macOS lock must include a lock that exists"

    packages = _lock_packages()
    for name, (version, block) in _pins(FREEZER_LOCKS[1]).items():
        assert _HASH.search(block), f"macOS-only pin without a hash: {name}=={version}"
        locked = packages.get(name)
        assert locked is not None and locked["version"] == version, (
            f"macOS-only pin {name}=={version} contradicts uv.lock"
        )
