import assert from 'node:assert/strict';
import test from 'node:test';
import { GeneratedReviewController } from '../.out/renderer/generated-review.js';
const track = (id) => ({id:id.repeat(64),title:id,artist:'DJ',bpm:120,key:'8A',energy:5,duration:120});
const review = (id='review-1') => ({reviewId:id,tracks:[track('a'),track('b'),track('c')],name:'Set',variant:'balanced',warnings:[],blockers:[],readiness:'ready',qualityScore:.8,transitions:[],readinessChecks:[{label:'Metadata',status:'ready',detail:'Complete'}],readinessSummary:'Ready',engineFacts:'Local engine: 3 tracks',protectedTrackIds:[]});
function fixture(overrides={}) {
 const calls=[];let current=review();let enabled=true;
 const api={reviewDetails:async(i)=>{calls.push(['details',i]);return current;},reviewCompare:async(i)=>{calls.push(['compare',i]);return {reviewId:i.reviewId,available:true,replacement:track('d'),message:'Preview only',original:current,proposed:current};},reviewRemove:async(i)=>{calls.push(['remove',i]);return review('review-2');},reviewReorder:async(i)=>{calls.push(['reorder',i]);return {...review('review-2'),tracks:i.trackIds.map(id=>current.tracks.find(t=>t.id===id))};},...overrides};
 const controller=new GeneratedReviewController(api,{current:()=>current,canAct:()=>enabled,changed:()=>{},applied:v=>{current=v;},perform:async(_label,task,apply,fail)=>{try{apply(await task());}catch(error){fail(error);}}});
 return {controller,calls,get current(){return current;},change:v=>{current=v;},block:()=>{enabled=false;}};
}
test('offline compare is read-only and remove sends exact revision and replaces current review',async()=>{const f=fixture();await f.controller.compare('b'.repeat(64));assert.equal(f.current.reviewId,'review-1');assert.equal(f.controller.comparison.replacement.id,'d'.repeat(64));await f.controller.remove('b'.repeat(64));assert.equal(f.current.reviewId,'review-2');assert.equal(f.controller.comparison,null);assert.deepEqual(f.calls[1],['remove',{reviewId:'review-1',trackId:'b'.repeat(64)}]);});
test('pending requests prevent repeats and late replies cannot replace newer review',async()=>{let finish;const f=fixture({reviewRemove:()=>new Promise(resolve=>{finish=resolve;})});const pending=f.controller.remove('b'.repeat(64));assert.equal(f.controller.pending,true);await f.controller.remove('b'.repeat(64));f.change(review('newer'));finish(review('late'));await pending;assert.equal(f.current.reviewId,'newer');assert.equal(f.controller.pending,false);});
test('moves use exact current permutation and saved or blocked host cannot edit',async()=>{const f=fixture();await f.controller.move('b'.repeat(64),-1);assert.deepEqual(f.calls[0][1].trackIds,['b','a','c'].map(x=>x.repeat(64)));f.change({...review(),variant:'saved'});await f.controller.remove('a'.repeat(64));assert.equal(f.calls.length,1);f.change(review());f.block();await f.controller.compare('a'.repeat(64));assert.equal(f.calls.length,1);});
test('failure does not leak paths and keeps current revision',async()=>{const f=fixture({reviewRemove:async()=>{throw Object.assign(new Error('/private/path'),{code:'protected_track'});}});await f.controller.remove('a'.repeat(64));assert.equal(f.current.reviewId,'review-1');assert.match(f.controller.error,/protegida/i);assert.doesNotMatch(f.controller.error,/private/);});
