import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {LegacyImportHost}=require('../.out/main/legacy-import-host.js');
const preview={previewId:'a'.repeat(32),mode:'fresh-profile-only',trackCount:1,cachedTrackCount:1,playlistCount:1,referenceCount:1,playlistNames:['Set'],safePreferences:{previewVolume:.4,spectralCohesion:.8},requiresRootAuthorization:true,sourceUnchanged:true};
const success={imported:true,restartRequired:true,backupRetained:true,requiresRootAuthorization:true,trackCount:1,playlistCount:1};
function fixture(overrides={}){const calls=[];const host=new LegacyImportHost({chooseDirectory:async()=>'/native/selected',request:async(method,params)=>{calls.push([method,params]);return method==='legacy.preview'?{...preview,privatePath:'/never-return'}:method==='legacy.apply'?success:{discarded:true};},confirm:async()=>true,canStart:()=>true,isClosing:()=>false,...overrides});return {host,calls};}
test('native source alone reaches preview and native confirmation alone adds authority',async()=>{const {host,calls}=fixture();assert.deepEqual(await host.preview(),preview);assert.deepEqual(calls[0],['legacy.preview',{source:'/native/selected'}]);assert.deepEqual(await host.apply(preview.previewId),success);assert.deepEqual(calls[1],['legacy.apply',{previewId:preview.previewId,confirmed:true}]);assert.equal(host.restartRequired,true);await assert.rejects(host.preview(),/legacy_restart_required/);});
test('cancelled selection and confirmation never commit and forged IDs are rejected',async()=>{const cancelled=fixture({chooseDirectory:async()=>null});assert.deepEqual(await cancelled.host.preview(),{cancelled:true});assert.equal(cancelled.calls.length,0);const {host,calls}=fixture({confirm:async()=>false});await host.preview();await assert.rejects(host.apply('b'.repeat(32)),/stale_legacy/);assert.deepEqual(await host.apply(preview.previewId),{cancelled:true});assert.equal(calls.length,1);assert.deepEqual(await host.discard(preview.previewId),{discarded:true});await assert.rejects(host.apply(preview.previewId),/stale_legacy/);});
test('pending dialogs and commits remain exclusive; close drains and stops delayed approval',async()=>{let resolve,closing=false;const {host,calls}=fixture({confirm:async()=>new Promise(r=>resolve=r),isClosing:()=>closing});await host.preview();const apply=host.apply(preview.previewId);await new Promise(r=>setImmediate(r));assert.equal(host.busy,true);await assert.rejects(host.preview(),/busy/);closing=true;let drained=false;const shutdown=host.shutdown().then(()=>drained=true);await new Promise(r=>setImmediate(r));assert.equal(drained,false);resolve(true);await assert.rejects(apply,/core_stopped/);await shutdown;assert.equal(calls.length,1);assert.equal(host.busy,false);});
test('malformed backend summaries cannot authorize or reveal unknown fields',async()=>{const {host}=fixture({request:async()=>({...preview,trackCount:-1})});await assert.rejects(host.preview(),/legacy_invalid/);await assert.rejects(host.apply(preview.previewId),/stale_legacy/);const blocked=fixture({canStart:()=>false});await assert.rejects(blocked.host.preview(),/busy/);});
test('uncertain commit receipt or transport failure requires restart, known rollback does not',async()=>{for(const mode of ['receipt','transport','recovery']){const f=fixture({request:async method=>{if(method==='legacy.preview')return preview;if(mode==='receipt')return {imported:true};throw Object.assign(Error('failure'),{code:mode==='recovery'?'legacy_recovery_required':'core_stopped'});}});await f.host.preview();await assert.rejects(f.host.apply(preview.previewId),mode==='recovery'?/legacy_recovery_required/:/legacy_restart_required/);assert.equal(f.host.restartRequired,true);}const f=fixture({request:async method=>{if(method==='legacy.preview')return preview;throw Object.assign(Error('[legacy_import_failed]'),{code:'legacy_import_failed'});}});await f.host.preview();await assert.rejects(f.host.apply(preview.previewId),/legacy_import_failed/);assert.equal(f.host.restartRequired,false);});
