import test from 'node:test';import assert from 'node:assert/strict';
const {LegacyImportController}=await import('../.out/renderer/legacy-import.js');
const preview={previewId:'a'.repeat(32),mode:'fresh-profile-only',trackCount:1,cachedTrackCount:1,playlistCount:1,referenceCount:1,playlistNames:['Set'],safePreferences:{previewVolume:.4,spectralCohesion:.8},requiresRootAuthorization:true,sourceUnchanged:true};
const result={imported:true,restartRequired:true,backupRetained:true,requiresRootAuthorization:true,trackCount:1,playlistCount:1};
function fixture(overrides={}){let allowed=true,applied=0;const calls=[];const api={previewLegacyImport:async()=>{calls.push('preview');return preview;},applyLegacyImport:async input=>{calls.push(input);return result;},discardLegacyImport:async()=>({discarded:true}),...overrides};const controller=new LegacyImportController(api,{canAct:()=>allowed,changed:()=>{},applied:()=>{applied++;allowed=false;},perform:async(_,task,apply,fail)=>{try{apply(await task());}catch(error){fail(error);}}});return {controller,calls,get applied(){return applied;}};}
test('explicit selection creates preview, success freezes state and never forwards paths/confirmation',async()=>{const f=fixture();await f.controller.choose();assert.deepEqual(f.controller.preview,preview);await f.controller.apply();assert.equal(f.applied,1);assert.deepEqual(f.calls,['preview',{previewId:preview.previewId}]);assert.deepEqual(f.controller.result,result);assert.equal(f.controller.preview,null);await f.controller.choose();assert.equal(f.calls.length,2);});
test('cancelled native confirmation retains preview, discard clears it, retry has a new selection',async()=>{const f=fixture({applyLegacyImport:async()=>({cancelled:true})});await f.controller.choose();await f.controller.apply();assert.deepEqual(f.controller.preview,preview);assert.equal(f.applied,0);await f.controller.discard();assert.equal(f.controller.preview,null);assert.equal(f.controller.pending,false);});
test('repeated click cannot race a pending picker or commit; errors clear stale identity',async()=>{let finish;const f=fixture({previewLegacyImport:()=>new Promise(resolve=>finish=resolve)});const selection=f.controller.choose();await f.controller.choose();assert.equal(f.controller.pending,true);finish(preview);await selection;const stale=fixture({applyLegacyImport:async()=>{throw Object.assign(Error('/private'),'code' in {}?{}:{code:'stale_legacy'});}});await stale.controller.choose();await stale.controller.apply();assert.equal(stale.controller.preview,null);assert.match(stale.controller.error,/cambiaron/);assert.ok(!stale.controller.error.includes('/private'));});
test('recovery or uncertain commit locks UI rather than offering another import',async()=>{const f=fixture({applyLegacyImport:async()=>{throw Object.assign(Error('failure'),{code:'legacy_recovery_required'});}});await f.controller.choose();await f.controller.apply();assert.equal(f.applied,1);assert.match(f.controller.error,/recuperación/);});
