import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{LibraryHost}=require('../.out/main/library-host.js'),{LibraryWatch}=require('../.out/main/library-watch.js'),{validateRequest}=require('../.out/main/security.js');
function fixture({fail=false}={}){let enabled=true,roots=['/music'],cancelled=false,error=false;const calls=[];let events;const watch=new LibraryWatch((_roots,e)=>{events=e;if(fail)throw Error('native unavailable');e.ready(_roots);return {close:async()=>{calls.push('close');}};},()=>{});const host=new LibraryHost(watch,async(method,params)=>{calls.push(method);if(method==='settings.get')return {watchLibrary:enabled};if(method==='settings.update'){enabled=params.watchLibrary;return {watchLibrary:enabled};}if(method==='library.roots')return {roots};if(error)throw Error('scan failed');return {tracks:[],cancelled};});return {host,watch,calls,get events(){return events;},setRoots:v=>roots=v,cancel:()=>cancelled=true,fail:()=>error=true};}
test('initialize restores authorized roots and explicit scan clean survives failed native watching',async()=>{const f=fixture({fail:true});await f.host.initialize();assert.equal(f.host.status.changeState,'restored');assert.equal(f.host.status.watchState,'unavailable');await f.host.scan('/music');assert.equal(f.host.status.changeState,'clean');assert.equal(f.host.status.watchState,'unavailable');await f.host.close();});
test('scan pauses before Python and restarts after registered roots refresh; no arbitrary renderer roots',async()=>{const f=fixture();await f.host.initialize();const old=f.events;f.setRoots(['/music','/second']);await f.host.scan('/second');assert.ok(f.calls.indexOf('close')<f.calls.indexOf('library.scan'));assert.equal(f.host.status.changeState,'restored');old.change('/music');await f.host.rescan();assert.equal(f.host.status.changeState,'clean');assert.equal(f.host.status.rootCount,2);await f.host.close();});
test('cancellation and failure never publish clean and settings persist before reconfiguration',async()=>{const f=fixture();await f.host.initialize();f.cancel();await f.host.rescan();assert.equal(f.host.status.changeState,'restored');f.fail();await assert.rejects(f.host.scan('/music'),/scan failed/);assert.equal(f.host.status.changeState,'restored');await f.host.savePreferences({watchLibrary:false});assert.equal(f.host.status.watchState,'disabled');await f.host.close();});
test('settings/status/rescan IPC only accepts bounded preferences, never paths or capability flags',()=>{for(const method of ['getPreferences','getLibraryStatus','rescanLibrary']){assert.deepEqual(validateRequest(method),{});assert.throws(()=>validateRequest(method,{root:'/secret'}));}const good={revision:'a'.repeat(64),previewVolume:0.3,watchLibrary:true};assert.deepEqual(validateRequest('savePreferences',good),good);for(const p of [{...good,previewVolume:NaN},{...good,previewVolume:Infinity},{...good,previewVolume:-1},{...good,previewVolume:2},{...good,previewVolume:'0.5'},{...good,watchLibrary:1},{...good,revision:'bad'},{...good,providers:true},{...good,loudnessWriteback:true},{}])assert.throws(()=>validateRequest('savePreferences',p));assert.throws(()=>validateRequest('library.roots'));});
test('volume-only preference save keeps the active watcher generation and clean scan state',async()=>{const f=fixture();await f.host.initialize();await f.host.rescan();const closes=f.calls.filter(x=>x==='close').length;await f.host.savePreferences({watchLibrary:true,previewVolume:0.2});assert.equal(f.calls.filter(x=>x==='close').length,closes);assert.equal(f.host.status.changeState,'clean');await f.host.close();});
test('unavailable preferences do not hide registered roots or prevent an explicit manual rescan',async()=>{const watch=new LibraryWatch(()=>{throw Error('must remain disabled');},()=>{}),host=new LibraryHost(watch,async method=>{if(method==='settings.get')throw Error('unsafe preferences');if(method==='library.roots')return {roots:['/music']};return {tracks:[],cancelled:false};});await host.initialize();assert.equal(host.status.rootCount,1);assert.equal(host.status.watchState,'disabled');await host.rescan();assert.equal(host.status.changeState,'clean');await host.close();});
