import assert from 'node:assert/strict';
import test from 'node:test';
import { createLibraryStatusView } from '../.out/renderer/library-status.js';
class Element extends EventTarget { children = []; attrs = {}; textContent = ''; disabled = false; hidden = false; setAttribute(key, value) { this.attrs[key] = String(value); } append(...children) { this.children.push(...children); } replaceChildren(...children) { this.children = children; } set innerHTML(_) { throw new Error('Unsafe HTML'); } }
const all = (node) => [node, ...node.children.flatMap(all)]; const text = (node) => [node.textContent, ...node.children.map(text)].join(' ');
function fixture() { const previous = globalThis.document; globalThis.document = { createElement: () => new Element() }; const root = new Element(); let enabled = true; let rescans = 0; const render = createLibraryStatusView(root, { canAct: () => enabled, rescan: () => { rescans++; } }); const state = { revision: 1, changeState: 'clean', watchState: 'active', rootCount: 2, watchedCount: 2 }; render(state); return { root, state, render, get: (id) => all(root).find((node) => node.id === `library-status-${id}`), rescans: () => rescans, block: () => { enabled = false; render(state); }, restore: () => { globalThis.document = previous; } }; }
test('completed clean scan remains clean when watching is unavailable, with separate future-change warning', () => {
  const f = fixture(); try { f.render({ ...f.state, watchState: 'unavailable', watchedCount: 0 }); assert.match(f.get('changes').textContent, /Escaneo completado/); assert.match(f.get('changes').textContent, /No se han detectado cambios/); assert.match(f.get('watch').textContent, /futuros|futuras/); assert.doesNotMatch(f.get('changes').textContent, /pendiente|cambios detectados|sin verificar/i); assert.equal(f.state.changeState, 'clean'); } finally { f.restore(); }
});
test('restored is explicitly unverified, changed stays changed across watch states, and counts never reveal paths', () => {
  const f = fixture(); try { f.render({ ...f.state, changeState: 'restored', watchState: 'starting' }); assert.match(f.get('changes').textContent, /reinicio|reiniciar/); assert.match(f.get('changes').textContent, /verificad/i); for (const watchState of ['starting', 'active', 'disabled', 'unavailable', 'paused']) { f.render({ ...f.state, changeState: 'changed', watchState }); assert.match(f.get('changes').textContent, /cambios/i); assert.match(f.get('changes').textContent, /escanear/i); assert.ok(f.get('watch').textContent); } assert.match(text(f.root), /2/); } finally { f.restore(); }
});
test('status and rescan are separate from operation progress, gated by availability and known roots', () => {
  const f = fixture(); try { assert.equal(f.get('banner').attrs['aria-live'], 'polite'); f.get('rescan').dispatchEvent(new Event('click')); assert.equal(f.rescans(), 1); f.block(); assert.equal(f.get('rescan').disabled, true); f.get('rescan').dispatchEvent(new Event('click')); assert.equal(f.rescans(), 1); assert.match(f.get('changes').textContent, /Escaneo completado/); f.render({ ...f.state, rootCount: 0, watchedCount: 0 }); assert.equal(f.get('rescan').disabled, true); f.render(null); assert.equal(f.get('rescan').disabled, true); assert.match(text(f.root), /disponible|cargando/i); } finally { f.restore(); }
});
