import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{LoudnessHost}=require('../.out/main/loudness-host.js'),{validateRequest}=require('../.out/main/security.js');
const id='11111111-1111-4111-8111-111111111111',track='a'.repeat(64),deferred=()=>{let resolve;return {promise:new Promise(r=>{resolve=r;}),resolve:value=>resolve(value)};};
function fixture(){const calls=[];let confirmed=true,closing=false;const status={tracks:[]};let run=async()=>({cancelled:false,changedCount:1,status});let confirmation=async()=>confirmed;const host=new LoudnessHost({request:async(method,params)=>{calls.push([method,params]);if(method==='loudness.preview')return {previewId:id,trackCount:1};if(method==='loudness.confirmation')return {previewId:id,trackCount:1,folders:['/owned/music'],backupDirectory:'/owned/data/loudness-backups'};if(method==='loudness.run')return run();return status;},confirm:summary=>{calls.push(['dialog',summary]);return confirmation();},cancel:async()=>{calls.push(['cancel']);return {cancelled:true};},isClosing:()=>closing});return {host,calls,status,refuse:()=>confirmed=false,close:()=>closing=true,holdRun:value=>run=()=>value,holdConfirm:value=>confirmation=()=>value};}
test('readonly preview and refused native confirmation never issue a run',async()=>{const f=fixture();await f.host.preview({trackIds:[track],force:false});f.refuse();const result=await f.host.run(id);assert.equal(result.cancelled,true);assert.equal(result.changedCount,0);assert.ok(!f.calls.some(([method])=>method==='loudness.run'));});
test('only exact main-owned preview may reach native confirmation and confirmed backend run',async()=>{const f=fixture();await assert.rejects(f.host.run(id));await f.host.preview({trackIds:[track],force:false});const result=await f.host.run(id);assert.equal(result.changedCount,1);assert.deepEqual(f.calls.find(([m])=>m==='loudness.run'),['loudness.run',{previewId:id,confirmed:true}]);assert.equal(f.host.busy,false);});
test('cancel while native confirmation is pending prevents a later affirmative response from writing',async()=>{const f=fixture(),wait=deferred();f.holdConfirm(wait.promise);await f.host.preview({trackIds:[track],force:false});const work=f.host.run(id);await new Promise(r=>setImmediate(r));assert.deepEqual(await f.host.cancel(),{cancelled:true});wait.resolve(true);assert.equal((await work).cancelled,true);assert.ok(!f.calls.some(([m])=>m==='loudness.run'));});
test('close cancels active analysis but waits for its actual commit/run boundary',async()=>{const f=fixture(),wait=deferred();f.holdRun(wait.promise);await f.host.preview({trackIds:[track],force:false});const work=f.host.run(id);await new Promise(r=>setImmediate(r));let closed=false;const close=f.host.shutdown().then(()=>closed=true);await new Promise(r=>setImmediate(r));assert.equal(closed,false);assert.ok(f.calls.some(([m])=>m==='cancel'));wait.resolve({cancelled:true,changedCount:1,status:f.status});await Promise.all([work,close]);assert.equal(closed,true);});
test('closing before confirmation returns never starts a writer',async()=>{const f=fixture(),wait=deferred();f.holdConfirm(wait.promise);await f.host.preview({trackIds:[track],force:false});const work=f.host.run(id);await new Promise(r=>setImmediate(r));f.close();wait.resolve(true);await assert.rejects(work);assert.ok(!f.calls.some(([m])=>m==='loudness.run'));});
test('loudness IPC is finite bounded and path/confirmed/command free',()=>{assert.deepEqual(validateRequest('getLoudnessStatus'),{});assert.deepEqual(validateRequest('previewLoudness',{trackIds:[track],force:false}),{trackIds:[track],force:false});assert.deepEqual(validateRequest('runLoudness',{previewId:id}),{previewId:id});const settings={revision:track,enabled:true,targetLufs:-10,toleranceLu:2};assert.deepEqual(validateRequest('saveLoudnessSettings',settings),settings);for(const p of [{...settings,targetLufs:NaN},{...settings,targetLufs:-31},{...settings,toleranceLu:11},{...settings,enabled:1},{...settings,path:'/private'},{}])assert.throws(()=>validateRequest('saveLoudnessSettings',p));for(const p of [{trackIds:[],force:false},{trackIds:[track,track],force:false},{trackIds:[track,'b'.repeat(64)],force:true},{trackIds:[track],force:1},{trackIds:[track],force:false,confirmed:true}])assert.throws(()=>validateRequest('previewLoudness',p));assert.throws(()=>validateRequest('runLoudness',{previewId:id,confirmed:true}));assert.throws(()=>validateRequest('loudness.confirmation',{previewId:id}));});
