import assert from 'node:assert/strict';import test from 'node:test';
import {OfflineBrowseView} from '../.out/renderer/offline-browse.js';
class Element extends EventTarget{constructor(tag='div'){super();this.tagName=tag;}children=[];attrs={};dataset={};textContent='';value='';checked=false;disabled=false;hidden=false;setAttribute(k,v){this.attrs[k]=String(v);}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}set innerHTML(_){throw Error('No HTML');}}
const all=node=>[node,...node.children.flatMap(all)];const tick=()=>new Promise(r=>setImmediate(r));
function fixture(patch={}){const old=globalThis.document;globalThis.document={createElement:tag=>new Element(tag)};const library=new Element(),saved=new Element(),cards=new Element();const calls=[];let active=true;const api={queryLibrary:async p=>{calls.push(['query',p]);return {tracks:[{id:'a'.repeat(64),title:'Known'}],query:{genre:'House',bpm_min:120,bpm_max:128,interpretation_note:'Editable suggestion'},genres:['House'],matchedCount:1,totalCount:4,suppressedCount:1};},searchPlaylists:async p=>{calls.push(['search',p]);return [{id:'2',name:'Second'}];},comparePlaylists:async p=>{calls.push(['compare',p]);return {comparison:'1 shared unique track; <img>'};},deletePlaylist:async p=>{calls.push(['delete',p]);return {deletionId:'token',name:'Second'};},listDeletedPlaylists:async()=>[{deletionId:'archive',name:'Old',trackCount:3,deletedAt:'date'}],restorePlaylist:async p=>{calls.push(['restore',p]);return {id:'9',name:'Old',trackCount:3,createdAt:'date'};},...patch};const view=new OfflineBrowseView(library,saved,api,{canAct:()=>active,canDelete:()=>true,perform:async(_label,task,apply)=>apply(await task(),true),libraryChanged:v=>calls.push(['library',v]),savedChanged:()=>calls.push(['savedChanged']),deleted:id=>calls.push(['deleted',id]),restored:p=>calls.push(['restored',p])});const get=id=>all(library).concat(all(saved),all(cards)).find(n=>n.id===id);const click=id=>{assert.ok(get(id),id);get(id).dispatchEvent(new Event('click'));};return{view,calls,library,saved,cards,get,click,block:()=>{active=false;view.sync();},restore:()=>globalThis.document=old};}
test('offline interpreted constraints populate editable manual values and safe display-only result',async()=>{const f=fixture();try{f.get('offline-library-request').value='House BPM 120-128';f.click('offline-library-interpret');await tick();assert.deepEqual(f.calls[0],['query',{request:'House BPM 120-128',sortBy:'title',descending:false,hideDuplicates:false}]);assert.equal(f.get('offline-library-bpm_min').value,'120');assert.equal(f.get('offline-library-genre').value,'House');assert.match(f.get('offline-library-status').textContent,/Editable suggestion/);f.get('offline-library-energy_min').value='5';f.get('offline-library-sort').value='bpm';f.get('offline-library-duplicates').checked=true;f.click('offline-library-apply');await tick();assert.equal(f.calls.findLast(([kind])=>kind==='query')[1].query.energy_min,5);assert.equal(f.calls.findLast(([kind])=>kind==='query')[1].hideDuplicates,true);f.click('offline-library-clear');assert.deepEqual(f.calls.at(-1),['library',null]);}finally{f.restore();}});
test('stale library replies after invalidation are discarded and busy actions do not dispatch',async()=>{let resolve;const f=fixture({queryLibrary:()=>new Promise(r=>resolve=r)});try{f.click('offline-library-apply');f.view.invalidateLibrary();resolve({tracks:[],query:{},genres:[],matchedCount:0,totalCount:0,suppressedCount:0});await tick();assert.equal(f.calls.filter(([kind])=>kind==='library').length,1);f.block();f.click('offline-library-apply');assert.equal(f.get('offline-library-apply').disabled,true);}finally{f.restore();}});
test('local saved search/compare, native deletion, and persistent recovery remain provider independent',async()=>{const f=fixture();try{for(const p of [{id:'1',name:'First',trackCount:1},{id:'2',name:'Second',trackCount:2}]){const card=new Element();f.view.addPlaylistActions(card,p);f.cards.append(card);}f.get('offline-saved-request').value='House';f.click('offline-saved-search');await tick();assert.equal(f.view.matches('1'),false);assert.equal(f.view.matches('2'),true);for(const id of ['1','2']){const checkbox=f.get('offline-saved-select-'+id);checkbox.checked=true;checkbox.dispatchEvent(new Event('change'));}f.click('offline-saved-compare');await tick();assert.deepEqual(f.calls.find(([kind])=>kind==='compare'),['compare',{playlistIds:['1','2']}]);assert.equal(f.get('offline-saved-result').textContent,'1 shared unique track; <img>');f.click('offline-saved-delete-2');await tick();assert.ok(f.calls.some(([kind,id])=>kind==='deleted'&&id==='2'));f.click('offline-saved-recovery');await tick();f.click('offline-saved-restore-archive');await tick();assert.deepEqual(f.calls.find(([kind])=>kind==='restore'),['restore',{deletionId:'archive'}]);assert.equal(f.calls.find(([kind])=>kind==='restored')[1].id,'9');}finally{f.restore();}});
test('cancelled deletion does not remove a card or fabricate recovery',async()=>{const f=fixture({deletePlaylist:async()=>({cancelled:true})});try{f.view.addPlaylistActions(f.cards,{id:'1',name:'Set',trackCount:2});f.click('offline-saved-delete-1');await tick();assert.equal(f.calls.some(([kind])=>kind==='deleted'),false);}finally{f.restore();}});
test('saved selection/deletion controls honor busy and dirty-draft protection after rerender',async()=>{const f=fixture();try{f.view.beginPlaylistRender([{id:'1',name:'Set',trackCount:1}]);f.view.addPlaylistActions(f.cards,{id:'1',name:'Set',trackCount:1});f.block();assert.equal(f.get('offline-saved-delete-1').disabled,true);assert.equal(f.get('offline-saved-select-1').disabled,true);f.click('offline-saved-delete-1');await tick();assert.equal(f.calls.some(([kind])=>kind==='delete'),false);}finally{f.restore();}});
test('dirty saved draft veto prevents deletion even with a direct click event',async()=>{const f=fixture();try{f.view.host.canDelete=()=>false;f.view.addPlaylistActions(f.cards,{id:'1',name:'Set',trackCount:1});f.view.sync();assert.equal(f.get('offline-saved-delete-1').disabled,true);f.click('offline-saved-delete-1');await tick();assert.equal(f.calls.some(([kind])=>kind==='delete'),false);}finally{f.restore();}});
test('only an accepted current sort restores keyboard focus; stale navigation never steals it',async()=>{
 const f=fixture();let focused=0;document.getElementById=()=>({focus:()=>focused++});try{
  f.view.host.perform=async(_label,task,apply)=>apply(await task(),false);await f.view.sortLibrary('bpm');assert.equal(focused,0);assert.equal(f.view.librarySort.field,null);
  f.view.host.perform=async(_label,task,apply)=>apply(await task(),true);await f.view.sortLibrary('bpm');assert.equal(focused,1);assert.equal(f.view.librarySort.field,'bpm');
  f.view.host.perform=async(_label,task,apply)=>{const result=await task();f.view.invalidateLibrary();apply(result,true);};await f.view.sortLibrary('bitrate');assert.equal(focused,1);assert.equal(f.view.librarySort.field,null);
 }finally{f.restore();}
});
