import assert from 'node:assert/strict';
import test from 'node:test';
import {OfflineHost} from '../.out/main/offline-host.js';
import {OFFLINE_FIELDS,validateOfflineRequest} from '../.out/main/offline-security.js';
const token='12345678-1234-1234-1234-123456789012';
const preview={previewId:token,playlistId:7,revision:'a'.repeat(64),name:'Exact set',trackCount:4};
function fixture(patch={}){const calls=[];const host=new OfflineHost({request:async(method,params)=>{calls.push([method,params]);if(method==='playlist.delete.preview')return preview;if(method==='playlist.delete.commit')return {deletionId:token,name:'Exact set'};if(method==='playlist.search')return {playlists:[{id:7,name:'Set',trackCount:2,updatedAt:'now'}]};if(method==='playlist.restore')return {id:8,name:'Set',trackCount:2,updatedAt:'then'};return {};},confirm:async summary=>{calls.push(['confirm',summary]);return true;},isClosing:()=>false,...patch});return {host,calls};}
test('native confirmation binds exact preview and never trusts a renderer confirmation',async()=>{const {host,calls}=fixture();assert.deepEqual(await host.delete('7'),{deletionId:token,name:'Exact set'});assert.deepEqual(calls,[['playlist.delete.preview',{playlistId:7}],['confirm',preview],['playlist.delete.commit',{previewId:token,confirmed:true}]]);assert.equal(host.busy,false);});
test('cancelled confirmation and close during dialog never commit',async()=>{const a=fixture({confirm:async()=>false});assert.deepEqual(await a.host.delete('7'),{cancelled:true});assert.equal(a.calls.length,1);let closing=false;const b=fixture({confirm:async()=>{closing=true;return true;},isClosing:()=>closing});await assert.rejects(b.host.delete('7'),/core_stopped/);assert.equal(b.calls.length,1);});
test('one busy host spans native dialog and shutdown drains active commit',async()=>{let confirm,commit;const f=fixture({confirm:()=>new Promise(r=>confirm=r),request:async method=>method==='playlist.delete.preview'?preview:new Promise(r=>commit=r)});const pending=f.host.delete('7');await new Promise(r=>setImmediate(r));assert.equal(f.host.busy,true);await assert.rejects(f.host.delete('7'),/busy/);confirm(true);await new Promise(r=>setImmediate(r));let drained=false;const shutdown=f.host.waitForCommit().then(()=>drained=true);await new Promise(r=>setImmediate(r));assert.equal(drained,false);commit({deletionId:token,name:'Exact set'});await pending;await shutdown;assert.equal(drained,true);});
test('main converts saved integer IDs; renderer never receives private backup paths',async()=>{const {host,calls}=fixture();assert.deepEqual(await host.search('House'),[{id:'7',name:'Set',trackCount:2,createdAt:'now'}]);assert.deepEqual(await host.restore(token),{id:'8',name:'Set',trackCount:2,createdAt:'then'});assert.deepEqual(calls[1],['playlist.restore',{deletionId:token}]);});
test('bridge validation is strict at nested query and identity boundaries',()=>{assert.deepEqual(OFFLINE_FIELDS.deletePlaylist,['playlistId']);for(const [method,params] of [['deletePlaylist',{playlistId:'7'}],['restorePlaylist',{deletionId:token}],['queryLibrary',{query:{bpm_min:120,bpm_max:128,energy_min:4,key:'8A'},sortBy:'bpm',descending:true,hideDuplicates:true}],['searchPlaylists',{request:''}],['comparePlaylists',{playlistIds:['1','2']}],['listDeletedPlaylists',{}]])assert.doesNotThrow(()=>validateOfflineRequest(method,params));for(const [method,params] of [['deletePlaylist',{playlistId:'/secret'}],['queryLibrary',{query:{path:'/secret'}}],['queryLibrary',{query:{bpm_min:130,bpm_max:120}}],['queryLibrary',{query:{key:'13A'}}],['queryLibrary',{hideDuplicates:'yes'}],['queryLibrary',{sortBy:'path'}],['queryLibrary',{query:{},request:'House'}],['comparePlaylists',{playlistIds:['1','1']}],['comparePlaylists',{playlistIds:['1']}],['restorePlaylist',{deletionId:'private/path'}]])assert.throws(()=>validateOfflineRequest(method,params));});
test('audio format and numeric bitrate are permitted global sort fields',()=>{
  for(const sortBy of ['format','bitrate'])assert.doesNotThrow(()=>validateOfflineRequest('queryLibrary',{sortBy,descending:true}));
  for(const sortBy of ['codec_path','audioFile','bitrateKbps;drop'])assert.throws(()=>validateOfflineRequest('queryLibrary',{sortBy}));
});
