import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,rm,readFile,readdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{PythonBridge}=require('../.out/main/bridge.js'),{OfflineHost}=require('../.out/main/offline-host.js');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),music=path.join(root,'desktop-electron/tests/fixtures/music'),python=process.env.XFIN_PYTHON;
const hash=async file=>createHash('sha256').update(await readFile(file)).digest('hex');
test('real Qt-free bridge filters/searches/compares and archives/restores exact saved tracks across restart',{skip:!python,timeout:30000},async()=>{
 const data=await realpath(await mkdtemp(path.join(os.tmpdir(),'xfin-offline-')));let core;const start=()=>new PythonBridge(python,['-m','xfinaudio.headless','--data-dir',data],{...process.env,PYTHONPATH:path.join(root,'src')});core=start();let confirmations=0;const host=()=>new OfflineHost({request:(method,params)=>core.request(method,params),confirm:async preview=>{confirmations++;assert.equal(preview.name,'Local set');assert.equal(preview.trackCount,4);return true;},isClosing:()=>false});
 const files=(await readdir(music)).map(name=>path.join(music,name)),before=await Promise.all(files.map(hash));
 try {
  const scan=await core.request('library.scan',{root:music});const filtered=await host().query({query:{bpm_min:120,bpm_max:128},sortBy:'bpm',descending:true,hideDuplicates:true});assert.ok(filtered.tracks.length>0);assert.ok(filtered.tracks.every(t=>t.bpm>=120&&t.bpm<=128));assert.equal(JSON.stringify(filtered).includes(music),false);
  const review=await core.request('prep.generate',{targetTrackCount:4,strategy:'harmonic_journey'});const saved=await core.request('playlist.save',{name:'Local set',reviewId:review.reviewId});const copy=await core.request('playlist.duplicate',{playlistId:saved.id});
  assert.equal((await host().search('Local set')).length,2);assert.match((await host().compare([String(saved.id),String(copy.id)])).comparison,/4 shared unique track/);
  const original=await core.request('playlist.edit.open',{playlistId:saved.id});const receipt=await host().delete(String(saved.id));assert.equal(confirmations,1);assert.equal((await core.request('playlist.list',{})).playlists.length,1);
  await core.close();core=start();const recovery=await host().deleted();assert.equal(recovery[0].deletionId,receipt.deletionId);const restored=await host().restore(receipt.deletionId);const opened=await core.request('playlist.edit.open',{playlistId:Number(restored.id)});assert.deepEqual(opened.tracks.map(t=>t.id),original.tracks.map(t=>t.id));assert.equal((await host().deleted()).length,0);assert.equal((await core.request('library.list',{})).tracks.length,scan.tracks.length);assert.deepEqual(await Promise.all(files.map(hash)),before);
 }finally{await core?.close();await rm(data,{recursive:true,force:true});}
});
