import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,rm,readFile,readdir,stat} from 'node:fs/promises';import {createHash,randomUUID} from 'node:crypto';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import path from 'node:path';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{PythonBridge}=require('../.out/main/bridge.js'),{ProfilesHost,profileProgress}=require('../.out/main/profiles-host.js'),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),python=process.env.XFIN_PYTHON;
test('real Qt-free profile host cancels/drains then completes original profiles, enables color strategies and persists without source writes',{skip:!python,timeout:180000},async()=>{
 const data=await realpath(await mkdtemp('/tmp/xfin-profiles-')),music=path.join(data,'audible');
 execFileSync(python,['-c',`import sys,pathlib,numpy as np,soundfile as sf\nfrom mutagen.flac import FLAC\nroot=pathlib.Path(sys.argv[1]);root.mkdir()\nrate=22050;t=np.arange(rate*70,dtype=np.float32)/rate;pulse=.2+.8*np.exp(-np.mod(t,.5)*15)\ny=(pulse*(np.sin(2*np.pi*120*t)+.2*np.sin(2*np.pi*240*t))).astype(np.float32)*.5\nfor index in range(3):\n p=root/f'audible-{index}.flac';sf.write(p,y,rate,subtype='PCM_16');tags=FLAC(p);tags.update({'title':f'Audible {index}','artist':'Synthetic','bpm':'120','initialkey':'8A','energylevel':'5'});tags.save()`,music]);
 const hashes=async()=>Promise.all((await readdir(music)).sort().map(async name=>{const file=path.join(music,name);return [name,createHash('sha256').update(await readFile(file)).digest('hex'),(await stat(file,{bigint:true})).mtimeNs];})),before=await hashes();
 const start=()=>new PythonBridge(python,['-m','xfinaudio.headless','--data-dir',path.join(data,'state')],{...process.env,PYTHONPATH:path.join(root,'src')});let core=start(),jobId='';
 try{
  assert.equal((await core.request('profiles.status')).state,'idle');const scanned=await core.request('library.scan',{root:music});assert.equal(scanned.tracks.length,3);
  const host=new ProfilesHost({request:(method,params)=>{jobId=randomUUID();return core.request(method,params,jobId);},cancel:()=>core.request('cancel',{jobId}),isClosing:()=>false});
  const cancelled=host.complete();await host.cancel();const receipt=await cancelled;assert.equal(receipt.cancelled,true);assert.equal(host.busy,false);assert.equal(receipt.status.state,'cancelled');
  const progress=[];core.on('progress',event=>{if(event.data?.phase==='profiles'){const safe=profileProgress(event.data);assert.ok(safe);progress.push(safe);}});
  const done=await host.complete();assert.equal(done.status.state,'complete');assert.equal(done.completeCount,3);assert.equal(done.incompleteCount,0);assert.equal(done.cancelled,false);assert.equal(done.status.spectralReadyCount,3);assert.equal(done.status.danceabilityReadyCount,3);assert.equal(done.status.edgeReadyCount,3);assert.deepEqual(done.tracks.map(track=>track.id),scanned.tracks.map(track=>track.id));assert.deepEqual([...new Set(progress.map(item=>item.stage))],['spectral','danceability','edge']);assert.equal(JSON.stringify(done).includes(music),false);
  const settings=await core.request('profiles.settings.get');assert.equal(settings.spectralCohesion,.5);await core.request('profiles.settings.update',{revision:settings.revision,spectralCohesion:.7});await assert.rejects(core.request('profiles.settings.update',{revision:settings.revision,spectralCohesion:.8}),error=>error.code==='stale_settings');
  for(const strategy of ['same_color','same_color_energy']){const review=await core.request('prep.generate',{targetTrackCount:3,strategy});assert.equal(review.tracks.length,3);assert.ok(review.reviewId);}
  await host.shutdown();await core.close();core=start();assert.equal((await core.request('profiles.status')).readyCount,3);assert.equal((await core.request('profiles.settings.get')).spectralCohesion,.7);const cached=await core.request('profiles.complete');assert.equal(cached.status.state,'complete');assert.deepEqual(await hashes(),before);
 }finally{await core.close();await rm(data,{recursive:true,force:true});}
});
