import assert from 'node:assert/strict';
import test from 'node:test';
class Element extends EventTarget {
  constructor(tag = 'div') { super(); this.tagName = tag; }
  textContent = ''; value = ''; checked = false; disabled = false; hidden = false; dataset = {}; children = []; attrs = {}; classes = new Set(); paused = true; duration = 0; currentTime = 0;
  classList = { toggle: (key, active) => active ? this.classes.add(key) : this.classes.delete(key), contains: (key) => this.classes.has(key) };
  setAttribute(key, value) { this.attrs[key] = value; } removeAttribute(key) { delete this.attrs[key]; }
  append(...nodes) { this.children.push(...nodes); } replaceChildren(...nodes) { this.children = nodes; } closest() { return null; } focus() {} pause() { this.paused = true; } load() {} async play() { this.paused = false; }
}
const all = (node) => [node, ...node.children.flatMap(all)]; const text = (node) => [node.textContent, ...node.children.map(text)].join(' ');
const tick = () => new Promise((resolve) => setImmediate(resolve)); const settle = async () => { for (let i = 0; i < 5; i++) await tick(); };
const prefs = (patch = {}) => ({ revision: 'a'.repeat(64), previewVolume: .25, watchLibrary: true, recoveryWarning: false, libraryLabels: ['DJ'], capabilities: { loudnessWriteback: false, providers: false, language: 'es' }, ...patch });
const status = (patch = {}) => ({ revision: 1, changeState: 'restored', watchState: 'active', rootCount: 1, watchedCount: 1, ...patch });
const tracks = ['a', 'b'].map((id) => ({ id: id.repeat(64), title: id, artist: 'DJ', bpm: 120, key: '8A', energy: 5, duration: 120, missing: false }));
const loudness = (patch = {}) => ({ revision: 'a'.repeat(64), enabled: true, targetLufs: -10, toleranceLu: 2, available: true, reason: 'ready', totalTracks: tracks.length, tracks: tracks.map((track) => ({ track, state: 'unmeasured', complete: false, lufs: null, lra: null, truePeak: null })), ...patch });
const receipt = (patch = {}) => ({ cancelled: false, changedCount: 1, unchangedCount: 1, failureCount: 0, backupCount: 1, status: loudness(), ...patch });
let sequence = 0;
async function fixture(overrides = {}) {
  const previousDocument = globalThis.document; const previousWindow = globalThis.window; const elements = new Map(); const calls = []; let onStatus; let progress; let statusUnsubscribed = false;
  const nodes = () => [...elements.values()].flatMap(all); const get = (id) => { const dynamic = nodes().find((node) => node.id === id); if (dynamic) return dynamic; if (!elements.has(id)) elements.set(id, new Element()); return elements.get(id); };
  const routes = ['library', 'preferences', 'loudness', 'playlists', 'editor', 'review', 'live', 'serato'].map((route) => { const button = new Element('button'); button.dataset.route = route; return button; });
  const api = {
    getLoudnessStatus: async () => { calls.push(['loudness']); return loudness(); },
    saveLoudnessSettings: async (input) => { calls.push(['saveLoudness', input]); return loudness({ ...input, revision: 'b'.repeat(64) }); },
    previewLoudness: async (input) => { calls.push(['previewLoudness', input]); return { previewId: '12345678-1234-4123-8123-123456789012', trackCount: input.trackIds.length, backupBytes: 2048, force: input.force, replaceComments: true, tracks: tracks.filter((track) => input.trackIds.includes(track.id)) }; },
    runLoudness: async (input) => { calls.push(['runLoudness', input]); return receipt(); },
    cancelCurrent: async () => { calls.push(['cancel']); },
    listLibrary: async () => { calls.push(['library']); return { tracks, count: 2 }; }, getPrepCatalog: async () => ({ strategies: [] }), onProgress: (callback) => { progress = callback; return () => {}; },
    getPreferences: async () => { calls.push(['preferences']); return prefs(); }, savePreferences: async (input) => { calls.push(['savePreferences', input]); return prefs({ ...input, revision: 'b'.repeat(64) }); },
    getLibraryStatus: async () => { calls.push(['status']); return status(); }, onLibraryStatus: (callback) => { onStatus = callback; return () => { statusUnsubscribed = true; }; },
    rescanLibrary: async () => { calls.push(['rescan']); return { tracks, count: 2 }; }, setDraftDirty: async (dirty) => { calls.push(['dirty', dirty]); },
    listPlaylists: async () => [{ id: '1', name: 'Set', trackCount: 2, createdAt: '' }], openPlaylistEditor: async () => ({ id: '1', editId: 'edit', revision: 'r1', name: 'Set', tracks, missingTrackCount: 0 }), discardPlaylistEdit: async () => ({ id: '1', editId: 'edit', revision: 'r1', name: 'Set', tracks, missingTrackCount: 0 }),
    generatePrep: async () => ({ reviewId: 'review', name: 'Set', variant: 'balanced', readiness: 'ready', tracks, warnings: [], blockers: [] }),
    openLive: async () => ({ sessionId: 'live', revision: 0, sourceReviewId: 'review', state: 'active', current: tracks[0], history: [], candidates: [{ track: tracks[1], score: 1, alerts: [] }], elapsedSeconds: 0 }),
    chooseSeratoDestination: async () => ({ destinationId: 'dest', label: '_Serato_' }), previewSeratoExport: async () => ({ previewId: 'preview', sourceRevision: 'r', filename: 'Set.crate', destinationLabel: '_Serato_', trackCount: 2, readiness: 'ready', warnings: [], blockers: [], canCommit: true, tracks, backup: { required: false } }), ...overrides,
  };
  globalThis.document = { getElementById: get, createElement: (tag) => new Element(tag), title: '', querySelectorAll: (selector) => selector === '[data-route]' || selector === '.nav-item' ? routes : selector === '[data-mutation]' ? nodes().filter((node) => 'mutation' in node.dataset) : selector === '[data-track-id]' ? nodes().filter((node) => 'trackId' in node.dataset) : [] };
  globalThis.window = Object.assign(new EventTarget(), { xfin: api }); get('metadata-filter').value = 'all'; get('prep-count').value = '2';
  await import(`../.out/renderer/app.js?loudnessApp=${++sequence}`); await settle();
  const click = (id) => get(id).dispatchEvent(new Event('click')); const navigate = async (route) => { routes.find((button) => button.dataset.route === route).dispatchEvent(new Event('click')); await settle(); };
  return { get, calls, nodes, click, navigate, progress: (event) => progress(event), event: (value) => { assert.equal(typeof onStatus, 'function'); onStatus(value); }, offline: () => progress({ operation: 'core', phase: 'error', message: '/private/core' }), statusUnsubscribed: () => statusUnsubscribed, generate: async () => { get('prep-form').dispatchEvent(new Event('submit', { cancelable: true })); await settle(); }, restore: () => { window.dispatchEvent(new Event('beforeunload')); globalThis.document = previousDocument; globalThis.window = previousWindow; } };
}
test('loudness loads only on demand and preserves unsaved settings through navigation', async () => {
  const f = await fixture(); try { assert.equal(f.calls.some(([kind]) => kind === 'loudness'), false); await f.navigate('loudness'); assert.equal(document.title, 'XfinAudio · Sonoridad'); assert.equal(f.calls.filter(([kind]) => kind === 'loudness').length, 1); f.get('loudness-target').value = '-14'; f.get('loudness-target').dispatchEvent(new Event('change')); await f.navigate('library'); await f.navigate('loudness'); assert.equal(f.get('loudness-target').value, '-14'); assert.match(f.get('loudness-dirty').textContent, /sin guardar/); assert.equal(f.calls.filter(([kind]) => kind === 'loudness').length, 1); } finally { f.restore(); }
});
test('editor, preferences and loudness dirtiness all protect the close guard', async () => {
  const f = await fixture(); try { await f.navigate('preferences'); f.get('preferences-volume').value = '.4'; f.get('preferences-volume').dispatchEvent(new Event('input')); await f.navigate('loudness'); f.get('loudness-target').value = '-12'; f.get('loudness-target').dispatchEvent(new Event('change')); await f.navigate('playlists'); f.nodes().find((node) => node.tagName === 'button' && node.textContent === 'Editar').dispatchEvent(new Event('click')); await settle(); f.get('editor-name').value = 'Conservar'; f.get('editor-name').dispatchEvent(new Event('input')); f.click('preferences-discard'); f.click('editor-discard'); await settle(); assert.equal(f.calls.filter(([kind]) => kind === 'dirty').at(-1)[1], true); f.click('loudness-discard'); assert.equal(f.calls.filter(([kind]) => kind === 'dirty').at(-1)[1], false); } finally { f.restore(); }
});
test('saving a real loudness policy invalidates existing review and Live without autoplay', async () => {
  const f = await fixture(); try { await f.generate(); f.click('start-live'); await settle(); assert.equal(f.get('live-content').hidden, false); await f.navigate('loudness'); f.get('loudness-target').value = '-12'; f.get('loudness-target').dispatchEvent(new Event('change')); f.click('loudness-save'); await settle(); assert.equal(f.get('review-content').hidden, true); assert.equal(f.get('live-content').hidden, true); assert.equal(f.get('audio-player').paused, true); assert.deepEqual(f.calls.find(([kind]) => kind === 'saveLoudness')[1], { revision: 'a'.repeat(64), enabled: true, targetLufs: -12, toleranceLu: 2 }); } finally { f.restore(); }
});
test('Run pauses preview, requires native-confirmed API path and retains zero-write native cancellation', async () => {
  let finish; const f = await fixture({ runLoudness: () => new Promise((resolve) => { finish = resolve; }) }); try { const play = f.nodes().find((node) => 'trackId' in node.dataset); play.dispatchEvent(new Event('click')); await settle(); assert.equal(f.get('audio-player').paused, false); await f.navigate('loudness'); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); assert.equal(f.get('audio-player').paused, false); f.click('loudness-run'); assert.equal(f.get('audio-player').paused, true); assert.equal(play.disabled, true); play.dispatchEvent(new Event('click')); assert.equal(f.get('audio-player').paused, true); assert.equal(f.get('cancel-operation').hidden, false); finish(receipt({ cancelled: true, changedCount: 0, unchangedCount: 0, backupCount: 0 })); await settle(); assert.match(f.get('loudness-result').textContent, /cancelada.*0 escrituras completadas.*0 copias/); assert.equal(f.get('audio-player').paused, true); assert.equal(f.get('cancel-operation').hidden, true); } finally { f.restore(); }
});
test('terminal partial receipt survives global cancellation and navigation with original backup counts', async () => {
  let finish; const f = await fixture({ runLoudness: () => new Promise((resolve) => { finish = resolve; }) }); try { await f.navigate('loudness'); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); f.click('loudness-run'); f.progress({ jobId: 'job', operation: 'loudness.run', phase: 'loudness', current: 1, total: 2 }); assert.match(f.get('operation-label').textContent, /sonoridad/i); assert.equal(f.get('operation-progress').value, 1); f.click('cancel-operation'); await f.navigate('library'); finish(receipt({ cancelled: true, unchangedCount: 0 })); await settle(); assert.match(f.get('loudness-result').textContent, /cancelada.*1 escrituras completadas.*1 copias/); assert.match(f.get('operation-detail').textContent, /conservan|completadas/); assert.equal(document.title, 'XfinAudio · Biblioteca'); assert.equal(f.get('loudness-preview-section').hidden, true); assert.equal(f.calls.filter(([kind]) => kind === 'cancel').length, 1); } finally { f.restore(); }
});
test('core disconnect retains terminal receipt but never revives stale status or hides offline notice', async () => {
  let finish; const f = await fixture({ runLoudness: () => new Promise((resolve) => { finish = resolve; }) }); try { await f.navigate('loudness'); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); f.click('loudness-run'); f.offline(); finish(receipt()); await settle(); assert.match(f.get('loudness-result').textContent, /1 escrituras completadas.*1 copias/); assert.equal(f.get('loudness-stale').hidden, false); assert.equal(f.get('loudness-refresh').disabled, true); assert.equal(f.get('operation-label').textContent, 'Servicio local desconectado'); assert.equal(f.get('loudness-preview-section').hidden, true); } finally { f.restore(); }
});
test('watch changes invalidate previews without losing settings draft; rescan invalidates scope before starting', async () => {
  const f = await fixture(); try { await f.navigate('loudness'); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); assert.equal(f.get('loudness-preview-section').hidden, false); f.event(status({ revision: 2, changeState: 'changed' })); assert.equal(f.get('loudness-preview-section').hidden, true); assert.equal(f.get('loudness-stale').hidden, false); f.click('loudness-refresh'); await settle(); f.get('loudness-target').value = '-13'; f.get('loudness-target').dispatchEvent(new Event('change')); f.event(status({ revision: 3, changeState: 'changed' })); assert.equal(f.get('loudness-target').value, '-13'); assert.match(f.get('loudness-dirty').textContent, /sin guardar/); f.click('loudness-discard'); f.click('loudness-refresh'); await settle(); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); f.click('library-status-rescan'); assert.equal(f.get('loudness-preview-section').hidden, true); await settle(); assert.equal(f.calls.some(([kind]) => kind === 'rescan'), true); } finally { f.restore(); }
});
test('dirty preferences or editor prevent analysis preview and run without losing drafts', async () => {
  const f = await fixture(); try { await f.navigate('loudness'); f.click('loudness-select-page'); await f.navigate('preferences'); f.get('preferences-volume').value = '.4'; f.get('preferences-volume').dispatchEvent(new Event('input')); await f.navigate('loudness'); f.click('loudness-preview'); await settle(); assert.equal(f.calls.some(([kind]) => kind === 'previewLoudness'), false); assert.match(f.get('loudness-draft-message').textContent, /Guarda o descarta/); assert.equal(f.get('preferences-volume').value, '0.4'); f.click('preferences-discard'); f.click('loudness-preview'); await settle(); await f.navigate('playlists'); f.nodes().find((node) => node.tagName === 'button' && node.textContent === 'Editar').dispatchEvent(new Event('click')); await settle(); f.get('editor-name').value = 'Pendiente'; f.get('editor-name').dispatchEvent(new Event('input')); await f.navigate('loudness'); f.click('loudness-run'); await settle(); assert.equal(f.calls.some(([kind]) => kind === 'runLoudness'), false); assert.match(f.get('loudness-draft-message').textContent, /Guarda o descarta/); assert.equal(f.get('editor-name').value, 'Pendiente'); } finally { f.restore(); }
});
test('post-write warning retains receipt but marks fallback tracks informational until explicit refresh', async () => {
  const warning = 'Conserva las copias de seguridad y vuelve a escanear antes de continuar.';
  const f = await fixture({ runLoudness: async () => receipt({ warning, status: loudness({ tracks: tracks.map((track) => ({ track: { ...track, title: 'Fallback desactualizado' }, state: 'unmeasured', complete: false, lufs: null, lra: null, truePeak: null })) }) }) }); try { await f.generate(); await f.navigate('loudness'); f.click('loudness-select-page'); f.click('loudness-preview'); await settle(); f.click('loudness-run'); await settle(); assert.match(f.get('loudness-result').textContent, /1 escrituras completadas.*1 copias/); assert.equal(f.get('loudness-result-warning').textContent, warning); assert.equal(f.get('loudness-stale').hidden, false); assert.equal(f.get('loudness-preview').disabled, true); assert.equal(f.get('review-content').hidden, true); assert.doesNotMatch(text(f.get('library-table')), /Fallback desactualizado/); f.click('loudness-refresh'); await settle(); assert.equal(f.get('loudness-stale').hidden, true); } finally { f.restore(); }
});
