import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,realpath,rm,readFile,readdir,cp} from 'node:fs/promises';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{PythonBridge}=require('../.out/main/bridge.js');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),music=path.join(root,'desktop-electron/tests/fixtures/music'),python=process.env.XFIN_PYTHON;
const hash=async file=>createHash('sha256').update(await readFile(file)).digest('hex');
test('real Qt-free generated evidence/compare/edit/save and persisted Prep controls retain exact source bytes across restart',{skip:!python,timeout:30000},async()=>{
 const data=await realpath(await mkdtemp(path.join(os.tmpdir(),'xfin-review-'))),copied=path.join(data,'music');await cp(music,copied,{recursive:true});const files=(await readdir(copied)).map(name=>path.join(copied,name)),before=await Promise.all(files.map(hash));
 const start=()=>new PythonBridge(python,['-m','xfinaudio.headless','--data-dir',path.join(data,'app')],{...process.env,PYTHONPATH:path.join(root,'src')});let core=start();
 try {
  const scan=await core.request('library.scan',{root:copied});const settings=await core.request('prep.settings.get');const persisted=await core.request('prep.settings.update',{revision:settings.revision,requiredTrackIds:[scan.tracks[0].id],excludedTrackIds:[scan.tracks.at(-1).id],genreFocus:'House',clearUnavailable:false});
  let review=await core.request('prep.generate',{targetTrackCount:4,name:'Editable',requiredTrackIds:persisted.requiredTrackIds,excludedTrackIds:persisted.excludedTrackIds,genreFocus:persisted.genreFocus});assert.equal(review.transitions.length,review.tracks.length-1);assert.ok(review.readinessChecks.length);assert.match(review.engineFacts,/Local engine/);assert.equal(JSON.stringify(review).includes(copied),false);
  const target=review.tracks.find(track=>!review.protectedTrackIds.includes(track.id));const comparison=await core.request('review.compare',{reviewId:review.reviewId,trackId:target.id});assert.equal(comparison.reviewId,review.reviewId);assert.match(comparison.message,/Preview|No eligible/);assert.equal((await core.request('review.details',{reviewId:review.reviewId})).reviewId,review.reviewId);
  const previous=review.reviewId;review=await core.request('review.remove',{reviewId:review.reviewId,trackId:target.id});assert.notEqual(review.reviewId,previous);assert.ok(review.tracks.every(track=>track.id!==target.id));await assert.rejects(core.request('playlist.save',{name:'stale',reviewId:previous}),error=>error.code==='stale_review');
  const order=review.tracks.map(track=>track.id);if(order.length>=3)[order[1],order[2]]=[order[2],order[1]];review=await core.request('review.reorder',{reviewId:review.reviewId,trackIds:order});assert.deepEqual(review.tracks.map(track=>track.id),order);const saved=await core.request('playlist.save',{name:'Edited',reviewId:review.reviewId});
  await core.close();core=start();assert.deepEqual(await core.request('prep.settings.get'),persisted);assert.deepEqual((await core.request('playlist.open',{playlistId:saved.id})).tracks.map(track=>track.id),order);assert.deepEqual(await Promise.all(files.map(hash)),before);
 }finally{await core.close();await rm(data,{recursive:true,force:true});}
});
