"""Playlist export and explainability helpers."""

from xfinaudio.exporting.explainability import PlaylistExplanation, TransitionExplanation, build_playlist_explanation
from xfinaudio.exporting.playlist_exporters import (
    ExporterRegistry,
    PlaylistExporter,
    default_exporter_registry,
    export_playlist_csv,
    export_playlist_json,
    export_playlist_m3u,
    export_quality_report_json,
    write_playlist_csv,
    write_playlist_json,
    write_playlist_m3u,
)
from xfinaudio.exporting.serato_crate import (
    SeratoExportPlan,
    SeratoWriteResult,
    build_serato_crate_bytes,
    plan_serato_crate_export,
    write_serato_crate,
)
from xfinaudio.exporting.serato_playlist_exporter import (
    SeratoLibrary,
    SeratoLibraryNotFoundError,
    discover_serato_libraries,
    plan_copilot_variant_serato_playlist_export,
    plan_generated_serato_playlist_export,
    plan_metadata_missing_field_serato_export,
    plan_metadata_status_serato_export,
    plan_serato_playlist_export,
    select_serato_library_for_tracks,
    to_serato_crate_path,
)

__all__ = [
    "ExporterRegistry",
    "PlaylistExplanation",
    "PlaylistExporter",
    "SeratoExportPlan",
    "SeratoLibrary",
    "SeratoLibraryNotFoundError",
    "SeratoWriteResult",
    "TransitionExplanation",
    "build_playlist_explanation",
    "build_serato_crate_bytes",
    "default_exporter_registry",
    "discover_serato_libraries",
    "export_playlist_csv",
    "export_playlist_json",
    "export_playlist_m3u",
    "export_quality_report_json",
    "plan_copilot_variant_serato_playlist_export",
    "plan_generated_serato_playlist_export",
    "plan_metadata_missing_field_serato_export",
    "plan_metadata_status_serato_export",
    "plan_serato_crate_export",
    "plan_serato_playlist_export",
    "select_serato_library_for_tracks",
    "to_serato_crate_path",
    "write_playlist_csv",
    "write_playlist_json",
    "write_playlist_m3u",
    "write_serato_crate",
]
