// Integration proof: execute with the INCLUDED Electron in Node mode; no system Node/Python/FFmpeg.
import assert from 'node:assert/strict';
import {access,cp,mkdir,readFile,readdir,realpath,rename,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import path from 'node:path';

const [bundleArg,fixtureArg,evidenceArg,profileArg]=process.argv.slice(2);
assert.ok(bundleArg&&fixtureArg&&evidenceArg&&profileArg,'Usage: smoke.mjs BUNDLE SYNTHETIC_MUSIC NEW_EVIDENCE_DIR SYNTHETIC_PROFILE_FIXTURES');
const evidence=path.resolve(evidenceArg),original=await realpath(bundleArg);
await mkdir(evidence);
const relocated=path.join(evidence,'relocated bundle with spaces'),music=path.join(evidence,'synthetic-music');
await cp(original,relocated,{recursive:true,verbatimSymlinks:true});
await cp(path.resolve(fixtureArg),music,{recursive:true});
const hidden=original+'.temporarily-hidden-for-relocation';
const report={checks:[],providerRequests:"none requested; AI remains disabled",fixtureSource:path.resolve(fixtureArg),path:''};
const hash=data=>createHash('sha256').update(data).digest('hex');
const files=(await readdir(music)).filter(name=>name.endsWith('.flac')).map(name=>path.join(music,name));
const hashes=await Promise.all(files.map(async file=>hash(await readFile(file))));
const data=path.join(evidence,'data'),emptyPath=path.join(evidence,'empty-bin');
await mkdir(emptyPath);report.path=emptyPath;
const hostileCache=path.join(evidence,'forbidden-inherited-cache');
const env={PATH:emptyPath,HOME:evidence,LANG:'C.UTF-8',XDG_CONFIG_HOME:path.join(evidence,'config'),NUMBA_CACHE_DIR:hostileCache,LIBROSA_CACHE_DIR:hostileCache,NUMBA_CACHE_LOCATOR_CLASSES:'hostile.NonexistentLocator'};
const require=createRequire(import.meta.url);
const {PythonBridge}=require(path.join(relocated,'resources/app/.out/main/bridge.js'));
const corePath=path.join(relocated,'resources/core/xfinaudio-core');
const ffmpeg=path.join(relocated,'resources/core/_internal/ffmpeg');
let core,moved=false;
const start=()=>new PythonBridge(corePath,['--data-dir',data],env);
const timeout=setTimeout(()=>{console.error('Runtime smoke timed out');process.exitCode=1;void core?.close();},300000);
const pcm=audio=>hash(execFileSync(ffmpeg,['-nostdin','-hide_banner','-loglevel','error','-i',audio,'-map','0:a:0','-f','s16le','-'],{env,maxBuffer:32*1024*1024}));
try{
  // Hiding the original prevents absolute build-path or original-bundle fallback.
  await rename(original,hidden);moved=true;
  core=start();
  const ai=await core.request('ai.status');assert.equal(ai.enabled,false);assert.equal(ai.configured,false);
  const scanned=await core.request('library.scan',{root:music});assert.equal(scanned.tracks.length,8);
  const metadata=await core.request('metadata.report');assert.ok(metadata);
  const catalog=await core.request('prep.catalog');assert.equal(catalog.strategies.length,11);
  const review=await core.request('prep.generate',{targetTrackCount:4,name:'Packaged fixture',strategy:'harmonic_journey'});
  assert.equal(review.readiness,'ready');assert.equal(review.tracks.length,4);
  const live=await core.request('live.open',{reviewId:review.reviewId});
  const next=await core.request('live.next',{sessionId:live.sessionId,revision:live.revision,trackId:live.candidates[0].track.id});
  assert.equal(next.revision,1);
  const saved=await core.request('playlist.save',{reviewId:review.reviewId,name:'Packaged fixture'});
  const duplicate=await core.request('playlist.duplicate',{playlistId:saved.id});
  const edit=await core.request('playlist.edit.open',{playlistId:duplicate.id});
  const edited=await core.request('playlist.edit.save',{editId:edit.editId,name:'Packaged edited copy',trackIds:edit.tracks.slice(0,2).map(track=>track.id)});
  assert.equal(edited.tracks.length,2);
  const preferences=await core.request('settings.get');
  await core.request('settings.update',{revision:preferences.revision,previewVolume:0.23,watchLibrary:false});
  await core.close();core=start();
  assert.equal((await core.request('settings.get')).previewVolume,0.23);
  assert.equal((await core.request('playlist.open',{playlistId:saved.id})).tracks.length,4);
  assert.equal((await core.request('playlist.open',{playlistId:duplicate.id})).tracks.length,2);
  assert.deepEqual(await Promise.all(files.map(async file=>hash(await readFile(file)))),hashes);
  report.checks.push('relocated core with empty PATH','offline AI defaults','metadata and 11 strategies','Prep, Live, playlist edit/persistence','preferences restart','read-only source hashes');
  const loudMusic=path.join(evidence,'synthetic-loudness');await mkdir(loudMusic);
  const audio=path.join(loudMusic,'owned-65s.wav'),before=await readFile(path.join(path.resolve(profileArg),'tone.wav'));await writeFile(audio,before);
  const decoded=pcm(audio),rows=await core.request('library.scan',{root:loudMusic});
  const track=rows.tracks.find(row=>row.title==='owned-65s'||row.filename==='owned-65s.wav'||row.path?.endsWith('owned-65s.wav'))??rows.tracks.find(row=>!scanned.tracks.some(previous=>previous.id===row.id));
  assert.ok(track,'Synthetic loudness track must be scanned');
  const status=await core.request('loudness.status');assert.equal(status.available,true);
  const preview=await core.request('loudness.preview',{trackIds:[track.id],force:false});
  assert.equal(hash(await readFile(audio)),hash(before));
  await assert.rejects(core.request('loudness.run',{previewId:preview.previewId,confirmed:false}));
  assert.equal(hash(await readFile(audio)),hash(before));
  const result=await core.request('loudness.run',{previewId:preview.previewId,confirmed:true});
  assert.equal(result.changedCount,1);assert.equal(result.backupCount,1);assert.equal(result.failureCount,0);
  assert.equal(pcm(audio),decoded);assert.notEqual(hash(await readFile(audio)),hash(before));
  const tagged=await readFile(audio);assert.ok(tagged.includes(Buffer.from("LUFS")));assert.ok(tagged.includes(Buffer.from("lufs=")));
  const measured=result.status.tracks.find(row=>row.track?.id===track.id)??result.status.tracks.find(row=>row.complete);
  assert.equal(measured.complete,true);assert.ok(Number.isFinite(measured.lufs));
  const runs=await readdir(path.join(data,'loudness-backups'));assert.equal(runs.length,1);
  const backupDir=path.join(data,'loudness-backups',runs[0]),backupFiles=(await readdir(backupDir)).filter(name=>name.endsWith('.bak'));
  assert.equal(backupFiles.length,1);assert.equal(hash(await readFile(path.join(backupDir,backupFiles[0]))),hash(before));
  const again=await core.request('loudness.preview',{trackIds:[track.id],force:false});
  const cached=await core.request('loudness.run',{previewId:again.previewId,confirmed:true});
  assert.equal(cached.changedCount,0);assert.equal(cached.backupCount,0);assert.equal(cached.unchangedCount,1);
  report.checks.push('bundled FFmpeg true-peak loudness','unconfirmed write rejected','exact original backup','metadata changed, decoded PCM identical','cached repeat has zero writes/backups');
  report.loudness={lufs:measured.lufs,decodedPcmSha256:decoded,originalSha256:hash(before),taggedSha256:hash(await readFile(audio))};
  await core.close();
  const profileMusic=path.join(evidence,'profile-fixtures'),profileData=path.join(evidence,'profile-data');
  await mkdir(profileMusic);
  const profileNames=['tone.wav','tone.flac','tone.mp3','tone.aac.m4a','tone.alac.m4a','tone.aiff'];
  for(const name of profileNames)await cp(path.join(path.resolve(profileArg),name),path.join(profileMusic,name));
  const profileHashes=await Promise.all(profileNames.map(async name=>hash(await readFile(path.join(profileMusic,name)))));
  core=new PythonBridge(corePath,['--data-dir',profileData],env);
  const profileScan=await core.request('library.scan',{root:profileMusic});assert.equal(profileScan.tracks.length,6);
  let profileEvents=0;core.on('progress',message=>{if(message.data?.phase==='profiles')profileEvents++;});
  const completed=await core.request('profiles.complete');
  assert.equal(completed.status.readyCount,6);assert.equal(completed.status.spectralReadyCount,6);
  assert.equal(completed.status.danceabilityReadyCount,6);assert.equal(completed.status.edgeReadyCount,6);
  assert.equal(completed.status.failedCount,0);assert.ok(profileEvents>0);
  await core.close();core=new PythonBridge(corePath,['--data-dir',profileData],env);
  assert.equal((await core.request('profiles.status')).readyCount,6);
  let repeatedEvents=0;core.on('progress',message=>{if(message.data?.phase==='profiles')repeatedEvents++;});
  assert.equal((await core.request('profiles.complete')).status.readyCount,6);assert.equal(repeatedEvents,0);
  assert.deepEqual(await Promise.all(profileNames.map(async name=>hash(await readFile(path.join(profileMusic,name))))),profileHashes);
  const codeCache=await readdir(path.join(profileData,'cache/numba'),{recursive:true});assert.ok(codeCache.some(name=>name.endsWith('.nbc')));
  await assert.rejects(access(hostileCache));
  report.profiles={...completed.status,unchangedHashes:profileHashes,jitCacheFiles:codeCache.length};
  report.checks.push('JIT code cache bound to app data; hostile inherited cache/locator ignored');
  report.checks.push('real spectral/danceability/edge completion across six formats','AAC/ALAC M4A bundled FFmpeg fallback','profile persistence and cache no-reanalysis','profile source hashes unchanged');
  report.passed=true;
}finally{
  clearTimeout(timeout);await core?.close();
  if(moved)await rename(hidden,original);
  await writeFile(path.join(evidence,'runtime-smoke.json'),JSON.stringify(report,null,2)+'\n');
}
console.log(JSON.stringify(report,null,2));
